server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/dev/native-file-repo
        git:
          uri: https://github.com/strongmhk/spring-cloud-config.git
#          password: mypassword
#          username: myusername
#          uri: file://Users/gacgonswacademy06/Documents/dev/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh