server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/strongmhk/spring-cloud-config.git
#          password: mypassword
#          username: myusername
#          uri: file://Users/gacgonswacademy06/Documents/dev/git-local-repo
